In [3]:
import pandas as pd
a=pd.read_csv('/content/train.csv')
print(a)

      battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  \
0               842     0          2.2         0   1       0           7   
1              1021     1          0.5         1   0       1          53   
2               563     1          0.5         1   2       1          41   
3               615     1          2.5         0   0       0          10   
4              1821     1          1.2         0  13       1          44   
...             ...   ...          ...       ...  ..     ...         ...   
1995            794     1          0.5         1   0       1           2   
1996           1965     1          2.6         1   0       0          39   
1997           1911     0          0.9         1   1       1          36   
1998           1512     0          0.9         0   4       1          46   
1999            510     1          2.0         1   5       1          45   

      m_dep  mobile_wt  n_cores  ...  px_height  px_width   ram  sc_h  sc_w  \
0       

In [4]:
y=a['price_range']
print(y)

0       1
1       2
2       2
3       2
4       1
       ..
1995    0
1996    2
1997    3
1998    0
1999    3
Name: price_range, Length: 2000, dtype: int64


In [11]:
print(max(y))
print(min(y))
x=a.drop(columns=['price_range'])

3
0


In [22]:
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler(feature_range=(0,1))
x_train=scaler.fit_transform(x)

In [23]:
print(x_train)

[[0.22778891 0.         0.68       ... 0.         0.         1.        ]
 [0.34736139 1.         0.         ... 1.         1.         0.        ]
 [0.04141617 1.         0.         ... 1.         1.         0.        ]
 ...
 [0.94188377 0.         0.16       ... 1.         1.         0.        ]
 [0.6753507  0.         0.16       ... 1.         1.         1.        ]
 [0.00601202 1.         0.6        ... 1.         1.         1.        ]]


In [25]:
from sklearn.model_selection import train_test_split
x=train_test_split(x_train)
print(x)

[array([[0.1008684 , 1.        , 0.76      , ..., 1.        , 0.        ,
        0.        ],
       [0.41883768, 1.        , 0.36      , ..., 1.        , 1.        ,
        0.        ],
       [0.57982632, 1.        , 0.48      , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.24448898, 1.        , 0.4       , ..., 1.        , 0.        ,
        0.        ],
       [0.85637943, 1.        , 0.        , ..., 0.        , 0.        ,
        1.        ],
       [0.41482966, 0.        , 0.28      , ..., 1.        , 1.        ,
        1.        ]]), array([[0.4742819 , 1.        , 0.28      , ..., 0.        , 1.        ,
        0.        ],
       [0.05678023, 0.        , 0.92      , ..., 0.        , 0.        ,
        0.        ],
       [0.8243153 , 1.        , 0.56      , ..., 1.        , 1.        ,
        0.        ],
       ...,
       [0.92117568, 1.        , 0.6       , ..., 0.        , 1.        ,
        0.        ],
       [0.18102872, 0.        , 0

In [40]:
import pandas as pd
a1=pd.read_csv('/content/heart.csv')
print(a1)
x=a1['target']
y=a1.drop(columns=['target'])

     age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3   
1     37    1   2       130   250    0        1      187      0      3.5   
2     41    0   1       130   204    0        0      172      0      1.4   
3     56    1   1       120   236    0        1      178      0      0.8   
4     57    0   0       120   354    0        1      163      1      0.6   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
298   57    0   0       140   241    0        1      123      1      0.2   
299   45    1   3       110   264    0        1      132      0      1.2   
300   68    1   0       144   193    1        1      141      0      3.4   
301   57    1   0       130   131    0        1      115      1      1.2   
302   57    0   1       130   236    0        0      174      0      0.0   

     slope  ca  thal  target  
0        0   0     1       1  
1        0   0     2     

In [41]:
print(x)
print(y)

0      1
1      1
2      1
3      1
4      1
      ..
298    0
299    0
300    0
301    0
302    0
Name: target, Length: 303, dtype: int64
     age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3   
1     37    1   2       130   250    0        1      187      0      3.5   
2     41    0   1       130   204    0        0      172      0      1.4   
3     56    1   1       120   236    0        1      178      0      0.8   
4     57    0   0       120   354    0        1      163      1      0.6   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
298   57    0   0       140   241    0        1      123      1      0.2   
299   45    1   3       110   264    0        1      132      0      1.2   
300   68    1   0       144   193    1        1      141      0      3.4   
301   57    1   0       130   131    0        1      115      1      1.2   
302   57    0   1       1

In [43]:
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler(feature_range=(0,1))
x1_train=scaler.fit_transform(x1)
print(x1_train)
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x1_train,y,test_size=0.3)
print(x_train.shape,y_train.shape,x_test.shape,y_test.shape)


[[0.70833333 1.         1.         ... 0.         0.         0.33333333]
 [0.16666667 1.         0.66666667 ... 0.         0.         0.66666667]
 [0.25       0.         0.33333333 ... 1.         0.         0.66666667]
 ...
 [0.8125     1.         0.         ... 0.5        0.5        1.        ]
 [0.58333333 1.         0.         ... 0.5        0.25       1.        ]
 [0.58333333 0.         0.33333333 ... 0.5        0.25       0.66666667]]
(212, 13) (212, 13) (91, 13) (91, 13)


In [44]:
import numpy as np
x1=x_train[0][0]
"""x2_p=[1]
y_p=[]
def preceptron(w1,w2,w3,b);
for i in range(len(x1));
z=1
print(x1)"""
print(x1)
print(x1.shape)


0.125
()
